services:
  - type: web
    name: youtube-api-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: 10000
      - key: YOUTUBE_COOKIE
        sync: false
